version: "3"

services:
  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    network_mode: bridge
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - testt

  webserver1:
    container_name: testt.dev.localhost
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=testt.dev.localhost
      - VIRTUAL_PORT=3000
    tty: true
    volumes:
      - ./testt/:/var/www/html/app
    networks:
      - testt

  webserver2:
    container_name: testt2.dev.localhost
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3001
    environment:
      - VIRTUAL_HOST=testt2.dev.localhost
      - VIRTUAL_PORT=3001
    tty: true
    volumes:
      - ./testt2/:/var/www/html/app
    networks:
      - testt

networks:
  testt:
    external: true
